### PR TITLE
added devcontainer

### PR DESCRIPTION
**Pull request by marc-hanheide**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This PR adds a devcontainer to ease development. This is the first step towards a proper containerised deployment of the pipeline. I adopted our standard ros2 repository structure from https://github.com/LCAS/ros2_pkg_template/tree/main, so the packages all reside in `src/` now, to allow the repository to also act as a ROS2 workspace.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Check this out @francescodelduchetto and @nikolauswagner

**Comment by marc-hanheide** [comment]
@nikolauswagner, @francescodelduchetto and @Iranaphor this PR is ready to be tried out. The devcontainer works for me now, including a stand alone version of CAR and a ros1 bridge. Ping me on teams on how to use it.

**Comment by nikolauswagner** [comment]
I'm having some issues in getting this to work. The docker configuration looks good to me, it spins up all the containers just fine, however I cannot access the CAR web interface as I'm getting a 404. I'm using the web UI port 8827 as per your configuration [here](https://github.com/LCAS/bayesian_topological_localisation/blob/4f7e351895f13439a58913df630ea99739fe7ced/.devcontainer/docker-compose.yaml#L37) (also double checked manually). The requests seem to go through to the container as the logs say:
> nginx-1                        | 172.19.0.1 - - [07/May/2024:14:29:37 +0000] "GET / HTTP/1.1" 302 145 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
> car-1                          | 172.19.0.4:42076 - - [07/May/2024 14:29:37] "HTTP/1.1 GET /rasberry/car" - 404 Not Found

Not sure if I'm missing something here? Is this an issue with my machine? Full logs below:
```
...>.devcontainer> docker compose up
WARN[0000] /home/niko/Documents/ros2/src/bayesian_topological_localisation/.devcontainer/docker-compose.yaml: `version` is obsolete 
[+] Running 8/3
 ✔ Container devcontainer-mosquitto-1                    Removed                                                                                                                                                      0.0s 
 ✔ Container devcontainer-car_forwards_WtoM-1            Removed                                                                                                                                                      0.0s 
 ✔ Container devcontainer-car_forwards_MtoW-1            Removed                                                                                                                                                      0.0s 
 ✔ Container devcontainer-ros_bridge-1                   Created                                                                                                                                                      0.0s 
 ✔ Container devcontainer-bayes_topological_localiser-1  Created                                                                                                                                                      0.0s 
 ✔ Container devcontainer-zenoh-1                        Created                                                                                                                                                      0.0s 
 ✔ Container devcontainer-car-1                          Created                                                                                                                                                      0.0s 
 ✔ Container devcontainer-nginx-1                        Created                                                                                                                                                      0.0s 
Attaching to bayes_topological_localiser-1, car-1, nginx-1, ros_bridge-1, zenoh-1
car-1                          | INFO:root:WebserverThread started.
car-1                          | INFO:root:NEW webserver running.
car-1                          | add /car/call_a_robot/www/static as static path
car-1                          | add /usr/local/lib/python2.7/dist-packages/webnsock/www/webnsock as static path
car-1                          | INFO:root:backend is running
car-1                          | http://0.0.0.0:8127/
zenoh-1                        |  * Starting: /zenoh-bridge-ros2dds -l tcp/0.0.0.0:7447 -r 0.0.0.0:8888 -d 0 -m peer
zenoh-1                        | [2024-05-07T14:23:26Z INFO  zenoh_bridge_ros2dds] zenoh-bridge-ros2dds v0.10.1-rc.2 built with rustc 1.72.0 (5680fa18f 2023-08-23)
zenoh-1                        | [2024-05-07T14:23:26Z INFO  zenoh::net::runtime] Using PID: 7ad8a8bbc909360b1abc7589e4967b01
zenoh-1                        | [2024-05-07T14:23:26Z INFO  zenoh::net::runtime::orchestrator] Zenoh can be reached at: tcp/172.20.0.4:7447
zenoh-1                        | [2024-05-07T14:23:26Z INFO  zenoh::net::runtime::orchestrator] Zenoh can be reached at: tcp/172.21.0.2:7447
zenoh-1                        | [2024-05-07T14:23:26Z INFO  zenoh::net::runtime::orchestrator] zenohd listening scout messages on 224.0.0.224:7446
nginx-1                        | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1                        | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1                        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1                        | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
nginx-1                        | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1                        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1                        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1                        | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: using the "epoll" event method
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: nginx/1.25.5
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: OS: Linux 6.5.0-28-generic
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker processes
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 22
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 23
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 24
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 25
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 26
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 27
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 28
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 29
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 30
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 31
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 32
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 33
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 34
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 35
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 36
nginx-1                        | 2024/05/07 14:23:26 [notice] 1#1: start worker process 37
zenoh-1                        | [2024-05-07T14:23:27Z INFO  tide::server] Server listening on http://0.0.0.0:8888
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] ROS2 plugin Config { id: None, namespace: "/", nodename: "zenoh_bridge_ros2dds", domain: 0, ros_localhost_only: false, allowance: None, pub_max_frequencies: [], transient_local_cache_multiplier: 10, queries_timeout: None, reliable_routes_blocking: true, __required__: None, __path__: None }
zenoh-1                        | 1715091807.103567 [0] async-std/: config: //CycloneDDS/Domain/General: 'NetworkInterfaceAddress': deprecated element (file:///etc/cyclonedds/cyclonedds.xml line 6)
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::discovered_entities] Discovered ROS Node /_ros2cli_daemon_0_e403ded1e2e04870bb96218c0d5047ad
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /_ros2cli_daemon_0_e403ded1e2e04870bb96218c0d5047ad declares Publisher /parameter_events: rcl_interfaces/msg/ParameterEvent - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Publisher (ROS:/parameter_events -> Zenoh:parameter_events) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /_ros2cli_daemon_0_e403ded1e2e04870bb96218c0d5047ad declares Publisher /rosout: rcl_interfaces/msg/Log - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Publisher (ROS:/rosout -> Zenoh:rosout) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::discovered_entities] Discovered ROS Node /bayesian_topological_localisation
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/set_parameters_atomically <-> Zenoh:bayesian_topological_localisation/set_parameters_atomically) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/get_parameters: rcl_interfaces/srv/GetParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/get_parameters <-> Zenoh:bayesian_topological_localisation/get_parameters) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/get_parameter_types: rcl_interfaces/srv/GetParameterTypes - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/get_parameter_types <-> Zenoh:bayesian_topological_localisation/get_parameter_types) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Publisher /rosout: rcl_interfaces/msg/Log - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Publisher /parameter_events: rcl_interfaces/msg/ParameterEvent - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/list_parameters: rcl_interfaces/srv/ListParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/list_parameters <-> Zenoh:bayesian_topological_localisation/list_parameters) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/describe_parameters: rcl_interfaces/srv/DescribeParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/describe_parameters <-> Zenoh:bayesian_topological_localisation/describe_parameters) created
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Service Server /bayesian_topological_localisation/set_parameters: rcl_interfaces/srv/SetParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/bayesian_topological_localisation/set_parameters <-> Zenoh:bayesian_topological_localisation/set_parameters) created
bayes_topological_localiser-1  | [INFO] [1715091807.330466025] [bayesian_topological_localisation]: Waiting for topological map...
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds] Node /bayesian_topological_localisation declares Subscriber /topological_map: topological_navigation_msgs/msg/TopologicalMap - Allowed
zenoh-1                        | [2024-05-07T14:23:27Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Subscriber (Zenoh:topological_map -> ROS:/topological_map) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::discovered_entities] Discovered ROS Node /ros_bridge
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Subscriber /parameter_events: rcl_interfaces/msg/ParameterEvent - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Subscriber (Zenoh:parameter_events -> ROS:/parameter_events) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/get_parameter_types: rcl_interfaces/srv/GetParameterTypes - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/get_parameter_types <-> Zenoh:ros_bridge/get_parameter_types) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/describe_parameters: rcl_interfaces/srv/DescribeParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/describe_parameters <-> Zenoh:ros_bridge/describe_parameters) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/list_parameters: rcl_interfaces/srv/ListParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/list_parameters <-> Zenoh:ros_bridge/list_parameters) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/set_parameters_atomically <-> Zenoh:ros_bridge/set_parameters_atomically) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Publisher /parameter_events: rcl_interfaces/msg/ParameterEvent - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/set_parameters: rcl_interfaces/srv/SetParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/set_parameters <-> Zenoh:ros_bridge/set_parameters) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Service Server /ros_bridge/get_parameters: rcl_interfaces/srv/GetParameters - Allowed
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Service Server (ROS:/ros_bridge/get_parameters <-> Zenoh:ros_bridge/get_parameters) created
zenoh-1                        | [2024-05-07T14:23:31Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Publisher /rosout: rcl_interfaces/msg/Log - Allowed
zenoh-1                        | [2024-05-07T14:23:32Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Publisher /rosout_agg: rcl_interfaces/msg/Log - Allowed
zenoh-1                        | [2024-05-07T14:23:32Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Publisher (ROS:/rosout_agg -> Zenoh:rosout_agg) created
zenoh-1                        | [2024-05-07T14:23:33Z INFO  zenoh_plugin_ros2dds] Node /ros_bridge declares Subscriber /rosout: rcl_interfaces/msg/Log - Allowed
zenoh-1                        | [2024-05-07T14:23:33Z INFO  zenoh_plugin_ros2dds::routes_mgr] Route Subscriber (Zenoh:rosout -> ROS:/rosout) created
nginx-1                        | 172.19.0.1 - - [07/May/2024:14:29:37 +0000] "GET / HTTP/1.1" 302 145 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
car-1                          | 172.19.0.4:42076 - - [07/May/2024 14:29:37] "HTTP/1.1 GET /rasberry/car" - 404 Not Found
```

**Comment by marc-hanheide** [comment]
you need to go to URL https://localhost:8827/raspberry/car or https://localhost:8827/raspberry/orders from the top of my head

**Comment by nikolauswagner** [comment]
I tried both of these (it also does automatically redirect me to /rasberry/car), it's just not loading the actual UI as its not finding the directories. Amie just confirmed that it's still working for her, so I assume the issue is on my side. I'll try to figure this out and will update you when resolved.

**Comment by nikolauswagner** [comment]
Was able to fix this now by building the CaR container first from the repository directly. Not sure why this helped, but the WebUI is working for me now.

**Pull request merged**
